apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        prarthanaus0597/gitops: true
        prarthanaus0597/https-github.com-prarthanaus0597-scientific_calculator: true
        prarthanaus0597/new: true
        prarthanaus0597/new2: true
        prarthanaus0597/new3: true
        prarthanaus0597/php-helloworld: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        prarthanaus0597/gitops: merge
        prarthanaus0597/https-github.com-prarthanaus0597-scientific_calculator: merge
        prarthanaus0597/new: merge
        prarthanaus0597/new2: merge
        prarthanaus0597/new3: merge
        prarthanaus0597/php-helloworld: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - prarthanaus0597/gitops
        - prarthanaus0597/https-github.com-prarthanaus0597-scientific_calculator
        - prarthanaus0597/new
        - prarthanaus0597/new2
        - prarthanaus0597/new3
        - prarthanaus0597/php-helloworld
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - prarthanaus0597/gitops
        - prarthanaus0597/https-github.com-prarthanaus0597-scientific_calculator
        - prarthanaus0597/new
        - prarthanaus0597/new2
        - prarthanaus0597/new3
        - prarthanaus0597/php-helloworld
      target_url: http://lighthouse-jx.192.168.49.2.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
