apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - prarthanaus0597/gitops
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - prarthanaus0597/gitops
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - prarthanaus0597/https-github.com-prarthanaus0597-scientific_calculator
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - prarthanaus0597/new
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - prarthanaus0597/new2
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - prarthanaus0597/new3
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - prarthanaus0597/new4
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - prarthanaus0597/php-helloworld
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - prarthanaus0597/react-quickstart
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    external_plugins:
      prarthanaus0597/gitops:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      prarthanaus0597/https-github.com-prarthanaus0597-scientific_calculator:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      prarthanaus0597/new:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      prarthanaus0597/new2:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      prarthanaus0597/new3:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      prarthanaus0597/new4:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      prarthanaus0597/php-helloworld:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      prarthanaus0597/react-quickstart:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      prarthanaus0597/gitops:
      - config-updater
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      prarthanaus0597/https-github.com-prarthanaus0597-scientific_calculator:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      prarthanaus0597/new:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      prarthanaus0597/new2:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      prarthanaus0597/new3:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      prarthanaus0597/new4:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      prarthanaus0597/php-helloworld:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      prarthanaus0597/react-quickstart:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - prarthanaus0597/gitops
      trusted_org: prarthanaus0597
    - repos:
      - prarthanaus0597/gitops
      trusted_org: prarthanaus0597
    - repos:
      - prarthanaus0597/https-github.com-prarthanaus0597-scientific_calculator
      trusted_org: prarthanaus0597
    - repos:
      - prarthanaus0597/new
      trusted_org: prarthanaus0597
    - repos:
      - prarthanaus0597/new2
      trusted_org: prarthanaus0597
    - repos:
      - prarthanaus0597/new3
      trusted_org: prarthanaus0597
    - repos:
      - prarthanaus0597/new4
      trusted_org: prarthanaus0597
    - repos:
      - prarthanaus0597/php-helloworld
      trusted_org: prarthanaus0597
    - repos:
      - prarthanaus0597/react-quickstart
      trusted_org: prarthanaus0597
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
